#!/usr/bin/env python3

import logging

from cert_checker import CertChecker

def main():
    logging.basicConfig(
        level=logging.WARNING,
        format='[%(asctime)s] [%(levelname)8s] [%(name)12s] %(message)s',
    )
    app = CertChecker()
    app.configure()
    app.run()

if __name__ == '__main__':
    main()
